namespace :import do
  desc "Imports data from a JSON file generated by scraping the Githb repo"
  task :import, [:file_name] => :environment do |task, args|
    data = JSON.parse(File.read(args[:file_name]))
    data.each do |item_type_name, item_type_value|
        puts item_type_name
    end
  end
end
