namespace :import do
  desc "Imports data from a JSON file generated by scraping the Githb repo"
  task :import, [:file_name] => :environment do |task, args|

	# creating a dummy user because Item needs some user
	user = User.find_or_create_by(nickname: 'learnawesome', auth0_uid: 'learnawesome', authinfo: 'learnawesome')

	data = JSON.parse(File.read(args[:file_name]))
	data.each do |idea_set_name, idea_set_value|
		idea_set_short_name = idea_set_name.split('/').last.sub('.html', '')
		idea_set = IdeaSet.find_or_create_by(name: idea_set_short_name)
		topic = Topic.find_or_create_by(name: idea_set_short_name, namespace: idea_set_name.sub('.html', ''))

		TopicIdeaSet.create!(topic: topic, idea_set: idea_set)

		idea_set_value.each do |item_type_name, item_types|
			item_type = ItemType.find_or_create_by(id: item_type_name.split(',').first.parameterize.underscore)
			item_type.update(display_name_plural: item_type_name)

			item_types.each do |item_hash|
				item = Item.create!(name: item_hash[:sourceText], idea_set: idea_set, item_type: item_type, user: user)
				Link.create!(item: item, url: item_hash[:url])

				puts "created Item #{item.name}"
			end
		end
	end
  end
end
