# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.delete_all
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

Link.delete_all
Item.delete_all
PersonIdeaSet.delete_all
TopicIdeaSet.delete_all
Person.delete_all
Topic.delete_all
IdeaSet.delete_all
ItemType.delete_all
Review.delete_all
User.delete_all
UserTopic.delete_all

# Create item types
ItemType.create!(id: 'app', display_name_plural: "Apps and Software Tools")
ItemType.create!(id: 'article', display_name_plural: "Articles and Essays")
ItemType.create!(id: 'audio', display_name_plural: "Audios and Podcasts")
ItemType.create!(id: 'blog', display_name_plural: "Blogs and Twitter feeds")
ItemType.create!(id: 'book', display_name_plural: "Books")
ItemType.create!(id: 'cert', display_name_plural: "Assessment and Certifications")
ItemType.create!(id: 'chat', display_name_plural: "Forums and Chat Groups")
ItemType.create!(id: 'cheatsheet', display_name_plural: "Cheatsheets")
ItemType.create!(id: 'code', display_name_plural: "Code")
ItemType.create!(id: 'conference', display_name_plural: "Conferences")
ItemType.create!(id: 'course', display_name_plural: "Courses and MOOCs")
ItemType.create!(id: 'flashcard', display_name_plural: "FlashCards")
ItemType.create!(id: 'game', display_name_plural: "Games")
ItemType.create!(id: 'image', display_name_plural: "Pictures and Infographics")
ItemType.create!(id: 'interactive', display_name_plural: "Interactives and Explorables")
ItemType.create!(id: 'journal', display_name_plural: "Journals and Magazines")
ItemType.create!(id: 'learning_plan', display_name_plural: "Learning Plans")
ItemType.create!(id: 'livestream', display_name_plural: "Livestreams")
ItemType.create!(id: 'meetup', display_name_plural: "Meetups")
ItemType.create!(id: 'newsletter', display_name_plural: "Newsletters")
ItemType.create!(id: 'people', display_name_plural: "People")
ItemType.create!(id: 'qna', display_name_plural: "Q & A forums")
ItemType.create!(id: 'quote', display_name_plural: "Quotes")
ItemType.create!(id: 'research_paper', display_name_plural: "Research Papers")
ItemType.create!(id: 'summary', display_name_plural: "Summary or notes")
ItemType.create!(id: 'video', display_name_plural: "Videos and Films")
ItemType.create!(id: 'website', display_name_plural: "Websites")
ItemType.create!(id: 'wiki', display_name_plural: "Wikis")

# Create topics imported from Git repo
Topic.create(name: 'abstract-algebra', 'search_index': 'abstract-algebra', namespace: nil, 'gitter_room': 'abstract-algebra')
Topic.create(name: 'academia', 'search_index': 'academia', namespace: nil, 'gitter_room': 'academia')
Topic.create(name: 'ai-ethics', 'search_index': 'ai-ethics', namespace: nil, 'gitter_room': 'ai-ethics')
Topic.create(name: 'alcohol', 'search_index': 'alcohol', namespace: nil, 'gitter_room': 'alcohol')
Topic.create(name: 'algebra', 'search_index': 'algebra', namespace: nil, 'gitter_room': 'algebra')
Topic.create(name: 'algorithms', 'search_index': 'algorithms', namespace: nil, 'gitter_room': 'algorithms')
Topic.create(name: 'amateur-radio', 'search_index': 'amateur-radio', namespace: nil, 'gitter_room': 'amateur-radio')
Topic.create(name: 'anatomy', 'search_index': 'anatomy', namespace: nil, 'gitter_room': 'anatomy')
Topic.create(name: 'animation', 'search_index': 'animation', namespace: nil, 'gitter_room': 'animation')
Topic.create(name: 'apple', 'search_index': 'apple', namespace: nil, 'gitter_room': 'apple')
Topic.create(name: 'architecture', 'search_index': 'architecture', namespace: nil, 'gitter_room': 'architecture')
Topic.create(name: 'arduino', 'search_index': 'arduino', namespace: nil, 'gitter_room': 'arduino')
Topic.create(name: 'art-craft', 'search_index': 'art-craft', namespace: nil, 'gitter_room': 'art-craft')
Topic.create(name: 'artificial-intelligence', 'search_index': 'artificial-intelligence', namespace: nil, 'gitter_room': 'artificial-intelligence')
Topic.create(name: 'astronomy', 'search_index': 'astronomy', namespace: nil, 'gitter_room': 'astronomy')
Topic.create(name: 'autobiography', 'search_index': 'autobiography', namespace: nil, 'gitter_room': 'autobiography')
Topic.create(name: 'aviation', 'search_index': 'aviation', namespace: nil, 'gitter_room': 'aviation')
Topic.create(name: 'awareness', 'search_index': 'awareness', namespace: nil, 'gitter_room': 'awareness')
Topic.create(name: 'basic-income', 'search_index': 'basic-income', namespace: nil, 'gitter_room': 'basic-income')
Topic.create(name: 'biblical-hermeneutics', 'search_index': 'biblical-hermeneutics', namespace: nil, 'gitter_room': 'biblical-hermeneutics')
Topic.create(name: 'bicycle', 'search_index': 'bicycle', namespace: nil, 'gitter_room': 'bicycle')
Topic.create(name: 'big-data', 'search_index': 'big-data', namespace: nil, 'gitter_room': 'big-data')
Topic.create(name: 'biographies', 'search_index': 'biographies', namespace: nil, 'gitter_room': 'biographies')
Topic.create(name: 'biology', 'search_index': 'biology', namespace: nil, 'gitter_room': 'biology')
Topic.create(name: 'bitcoin', 'search_index': 'bitcoin', namespace: nil, 'gitter_room': 'bitcoin')
Topic.create(name: 'blockchain', 'search_index': 'blockchain', namespace: nil, 'gitter_room': 'blockchain')
Topic.create(name: 'brain-computer-interface', 'search_index': 'brain-computer-interface', namespace: nil, 'gitter_room': 'brain-computer-interface')
Topic.create(name: 'buddhism', 'search_index': 'buddhism', namespace: nil, 'gitter_room': 'buddhism')
Topic.create(name: 'business', 'search_index': 'business', namespace: nil, 'gitter_room': 'business')
Topic.create(name: 'calculus', 'search_index': 'calculus', namespace: nil, 'gitter_room': 'calculus')
Topic.create(name: 'category-theory', 'search_index': 'category-theory', namespace: nil, 'gitter_room': 'category-theory')
Topic.create(name: 'chemistry', 'search_index': 'chemistry', namespace: nil, 'gitter_room': 'chemistry')
Topic.create(name: 'chess', 'search_index': 'chess', namespace: nil, 'gitter_room': 'chess')
Topic.create(name: 'code', 'search_index': 'code', namespace: nil, 'gitter_room': 'code')
Topic.create(name: 'combinatorics', 'search_index': 'combinatorics', namespace: nil, 'gitter_room': 'combinatorics')
Topic.create(name: 'comics', 'search_index': 'comics', namespace: nil, 'gitter_room': 'comics')
Topic.create(name: 'communicating', 'search_index': 'communicating', namespace: nil, 'gitter_room': 'communicating')
Topic.create(name: 'company-blogs', 'search_index': 'company-blogs', namespace: nil, 'gitter_room': 'company-blogs')
Topic.create(name: 'compilers', 'search_index': 'compilers', namespace: nil, 'gitter_room': 'compilers')
Topic.create(name: 'compression', 'search_index': 'compression', namespace: nil, 'gitter_room': 'compression')
Topic.create(name: 'computational-complexity', 'search_index': 'computational-complexity', namespace: nil, 'gitter_room': 'computational-complexity')
Topic.create(name: 'computer', 'search_index': 'computer', namespace: nil, 'gitter_room': 'computer')
Topic.create(name: 'computer-architecture', 'search_index': 'computer-architecture', namespace: nil, 'gitter_room': 'computer-architecture')
Topic.create(name: 'computer-graphics', 'search_index': 'computer-graphics', namespace: nil, 'gitter_room': 'computer-graphics')
Topic.create(name: 'computer-hardware', 'search_index': 'computer-hardware', namespace: nil, 'gitter_room': 'computer-hardware')
Topic.create(name: 'computer-memory', 'search_index': 'computer-memory', namespace: nil, 'gitter_room': 'computer-memory')
Topic.create(name: 'computer-networking', 'search_index': 'computer-networking', namespace: nil, 'gitter_room': 'computer-networking')
Topic.create(name: 'computer-science', 'search_index': 'computer-science', namespace: nil, 'gitter_room': 'computer-science')
Topic.create(name: 'computer-security', 'search_index': 'computer-security', namespace: nil, 'gitter_room': 'computer-security')
Topic.create(name: 'computer-vision', 'search_index': 'computer-vision', namespace: nil, 'gitter_room': 'computer-vision')
Topic.create(name: 'concurrency', 'search_index': 'concurrency', namespace: nil, 'gitter_room': 'concurrency')
Topic.create(name: 'consciousness', 'search_index': 'consciousness', namespace: nil, 'gitter_room': 'consciousness')
Topic.create(name: 'cooking', 'search_index': 'cooking', namespace: nil, 'gitter_room': 'cooking')
Topic.create(name: 'cosmetics', 'search_index': 'cosmetics', namespace: nil, 'gitter_room': 'cosmetics')
Topic.create(name: 'cpu', 'search_index': 'cpu', namespace: nil, 'gitter_room': 'cpu')
Topic.create(name: 'creativity', 'search_index': 'creativity', namespace: nil, 'gitter_room': 'creativity')
Topic.create(name: 'cryptocurrency', 'search_index': 'cryptocurrency', namespace: nil, 'gitter_room': 'cryptocurrency')
Topic.create(name: 'cryptography', 'search_index': 'cryptography', namespace: nil, 'gitter_room': 'cryptography')
Topic.create(name: 'culture', 'search_index': 'culture', namespace: nil, 'gitter_room': 'culture')
Topic.create(name: 'cybernetics', 'search_index': 'cybernetics', namespace: nil, 'gitter_room': 'cybernetics')
Topic.create(name: 'data-science', 'search_index': 'data-science', namespace: nil, 'gitter_room': 'data-science')
Topic.create(name: 'database-administrator', 'search_index': 'database-administrator', namespace: nil, 'gitter_room': 'database-administrator')
Topic.create(name: 'databases', 'search_index': 'databases', namespace: nil, 'gitter_room': 'databases')
Topic.create(name: 'decentralized-systems', 'search_index': 'decentralized-systems', namespace: nil, 'gitter_room': 'decentralized-systems')
Topic.create(name: 'deep-learning', 'search_index': 'deep-learning', namespace: nil, 'gitter_room': 'deep-learning')
Topic.create(name: 'design', 'search_index': 'design', namespace: nil, 'gitter_room': 'design')
Topic.create(name: 'digital-marketing', 'search_index': 'digital-marketing', namespace: nil, 'gitter_room': 'digital-marketing')
Topic.create(name: 'diy', 'search_index': 'diy', namespace: nil, 'gitter_room': 'diy')
Topic.create(name: 'drawing', 'search_index': 'drawing', namespace: nil, 'gitter_room': 'drawing')
Topic.create(name: 'drugs', 'search_index': 'drugs', namespace: nil, 'gitter_room': 'drugs')
Topic.create(name: 'earth', 'search_index': 'earth', namespace: nil, 'gitter_room': 'earth')
Topic.create(name: 'ebooks', 'search_index': 'ebooks', namespace: nil, 'gitter_room': 'ebooks')
Topic.create(name: 'economics', 'search_index': 'economics', namespace: nil, 'gitter_room': 'economics')
Topic.create(name: 'education', 'search_index': 'education', namespace: nil, 'gitter_room': 'education')
Topic.create(name: 'electrical-engineering', 'search_index': 'electrical-engineering', namespace: nil, 'gitter_room': 'electrical-engineering')
Topic.create(name: 'engineering', 'search_index': 'engineering', namespace: nil, 'gitter_room': 'engineering')
Topic.create(name: 'engineering-management', 'search_index': 'engineering-management', namespace: nil, 'gitter_room': 'engineering-management')
Topic.create(name: 'environment', 'search_index': 'environment', namespace: nil, 'gitter_room': 'environment')
Topic.create(name: 'ethics', 'search_index': 'ethics', namespace: nil, 'gitter_room': 'ethics')
Topic.create(name: 'evolution', 'search_index': 'evolution', namespace: nil, 'gitter_room': 'evolution')
Topic.create(name: 'expatriates', 'search_index': 'expatriates', namespace: nil, 'gitter_room': 'expatriates')
Topic.create(name: 'film-making', 'search_index': 'film-making', namespace: nil, 'gitter_room': 'film-making')
Topic.create(name: 'finance', 'search_index': 'finance', namespace: nil, 'gitter_room': 'finance')
Topic.create(name: 'freelancing', 'search_index': 'freelancing', namespace: nil, 'gitter_room': 'freelancing')
Topic.create(name: 'functional-programming', 'search_index': 'functional-programming', namespace: nil, 'gitter_room': 'functional-programming')
Topic.create(name: 'game-development', 'search_index': 'game-development', namespace: nil, 'gitter_room': 'game-development')
Topic.create(name: 'game-theory', 'search_index': 'game-theory', namespace: nil, 'gitter_room': 'game-theory')
Topic.create(name: 'games', 'search_index': 'games', namespace: nil, 'gitter_room': 'games')
Topic.create(name: 'gamification', 'search_index': 'gamification', namespace: nil, 'gitter_room': 'gamification')
Topic.create(name: 'garbage-collection', 'search_index': 'garbage-collection', namespace: nil, 'gitter_room': 'garbage-collection')
Topic.create(name: 'gardening', 'search_index': 'gardening', namespace: nil, 'gitter_room': 'gardening')
Topic.create(name: 'genealogy', 'search_index': 'genealogy', namespace: nil, 'gitter_room': 'genealogy')
Topic.create(name: 'geography', 'search_index': 'geography', namespace: nil, 'gitter_room': 'geography')
Topic.create(name: 'graphic-design', 'search_index': 'graphic-design', namespace: nil, 'gitter_room': 'graphic-design')
Topic.create(name: 'gymnastics', 'search_index': 'gymnastics', namespace: nil, 'gitter_room': 'gymnastics')
Topic.create(name: 'hacking', 'search_index': 'hacking', namespace: nil, 'gitter_room': 'hacking')
Topic.create(name: 'health', 'search_index': 'health', namespace: nil, 'gitter_room': 'health')
Topic.create(name: 'history', 'search_index': 'history', namespace: nil, 'gitter_room': 'history')
Topic.create(name: 'home-improvement', 'search_index': 'home-improvement', namespace: nil, 'gitter_room': 'home-improvement')
Topic.create(name: 'chinese', 'search_index': 'human-languages/chinese', namespace: 'human-languages', 'gitter_room': 'human-languages/chinese')
Topic.create(name: 'english', 'search_index': 'human-languages/english', namespace: 'human-languages', 'gitter_room': 'human-languages/english')
Topic.create(name: 'french', 'search_index': 'human-languages/french', namespace: 'human-languages', 'gitter_room': 'human-languages/french')
Topic.create(name: 'german', 'search_index': 'human-languages/german', namespace: 'human-languages', 'gitter_room': 'human-languages/german')
Topic.create(name: 'hindi', 'search_index': 'human-languages/hindi', namespace: 'human-languages', 'gitter_room': 'human-languages/hindi')
Topic.create(name: 'italian', 'search_index': 'human-languages/italian', namespace: 'human-languages', 'gitter_room': 'human-languages/italian')
Topic.create(name: 'japanese', 'search_index': 'human-languages/japanese', namespace: 'human-languages', 'gitter_room': 'human-languages/japanese')
Topic.create(name: 'kannada', 'search_index': 'human-languages/kannada', namespace: 'human-languages', 'gitter_room': 'human-languages/kannada')
Topic.create(name: 'russian', 'search_index': 'human-languages/russian', namespace: 'human-languages', 'gitter_room': 'human-languages/russian')
Topic.create(name: 'spanish', 'search_index': 'human-languages/spanish', namespace: 'human-languages', 'gitter_room': 'human-languages/spanish')
Topic.create(name: 'information-security', 'search_index': 'information-security', namespace: nil, 'gitter_room': 'information-security')
Topic.create(name: 'integrated-circuit-design', 'search_index': 'integrated-circuit-design', namespace: nil, 'gitter_room': 'integrated-circuit-design')
Topic.create(name: 'juggling', 'search_index': 'juggling', namespace: nil, 'gitter_room': 'juggling')
Topic.create(name: 'law', 'search_index': 'law', namespace: nil, 'gitter_room': 'law')
Topic.create(name: 'leadership', 'search_index': 'leadership', namespace: nil, 'gitter_room': 'leadership')
Topic.create(name: 'learning', 'search_index': 'learning', namespace: nil, 'gitter_room': 'learning')
Topic.create(name: 'lego', 'search_index': 'lego', namespace: nil, 'gitter_room': 'lego')
Topic.create(name: 'life', 'search_index': 'life', namespace: nil, 'gitter_room': 'life')
Topic.create(name: 'linear-algebra', 'search_index': 'linear-algebra', namespace: nil, 'gitter_room': 'linear-algebra')
Topic.create(name: 'linguistics', 'search_index': 'linguistics', namespace: nil, 'gitter_room': 'linguistics')
Topic.create(name: 'literature', 'search_index': 'literature', namespace: nil, 'gitter_room': 'literature')
Topic.create(name: 'logic', 'search_index': 'logic', namespace: nil, 'gitter_room': 'logic')
Topic.create(name: 'machine-learning', 'search_index': 'machine-learning', namespace: nil, 'gitter_room': 'machine-learning')
Topic.create(name: 'macos', 'search_index': 'macos', namespace: nil, 'gitter_room': 'macos')
Topic.create(name: 'magento', 'search_index': 'magento', namespace: nil, 'gitter_room': 'magento')
Topic.create(name: 'magic', 'search_index': 'magic', namespace: nil, 'gitter_room': 'magic')
Topic.create(name: 'management', 'search_index': 'management', namespace: nil, 'gitter_room': 'management')
Topic.create(name: 'marketing', 'search_index': 'marketing', namespace: nil, 'gitter_room': 'marketing')
Topic.create(name: 'martial-arts', 'search_index': 'martial-arts', namespace: nil, 'gitter_room': 'martial-arts')
Topic.create(name: 'mathematics', 'search_index': 'mathematics', namespace: nil, 'gitter_room': 'mathematics')
Topic.create(name: 'matrix', 'search_index': 'matrix', namespace: nil, 'gitter_room': 'matrix')
Topic.create(name: 'medicine', 'search_index': 'medicine', namespace: nil, 'gitter_room': 'medicine')
Topic.create(name: 'memoirs', 'search_index': 'memoirs', namespace: nil, 'gitter_room': 'memoirs')
Topic.create(name: 'mindset', 'search_index': 'mindset', namespace: nil, 'gitter_room': 'mindset')
Topic.create(name: 'minimalism', 'search_index': 'minimalism', namespace: nil, 'gitter_room': 'minimalism')
Topic.create(name: 'movies', 'search_index': 'movies', namespace: nil, 'gitter_room': 'movies')
Topic.create(name: 'music', 'search_index': 'music', namespace: nil, 'gitter_room': 'music')
Topic.create(name: 'technology', 'search_index': 'nations/china/technology', namespace: 'nations/china', 'gitter_room': 'nations/china/technology')
Topic.create(name: 'finance', 'search_index': 'nations/india/finance', namespace: 'nations/india', 'gitter_room': 'nations/india/finance')
Topic.create(name: 'history', 'search_index': 'nations/india/history', namespace: 'nations/india', 'gitter_room': 'nations/india/history')
Topic.create(name: 'natural-language-processing', 'search_index': 'natural-language-processing', namespace: nil, 'gitter_room': 'natural-language-processing')
Topic.create(name: 'nature', 'search_index': 'nature', namespace: nil, 'gitter_room': 'nature')
Topic.create(name: 'networking', 'search_index': 'networking', namespace: nil, 'gitter_room': 'networking')
Topic.create(name: 'neural-network', 'search_index': 'neural-network', namespace: nil, 'gitter_room': 'neural-network')
Topic.create(name: 'neuroscience', 'search_index': 'neuroscience', namespace: nil, 'gitter_room': 'neuroscience')
Topic.create(name: 'news', 'search_index': 'news', namespace: nil, 'gitter_room': 'news')
Topic.create(name: 'nutrition', 'search_index': 'nutrition', namespace: nil, 'gitter_room': 'nutrition')
Topic.create(name: 'open-data', 'search_index': 'open-data', namespace: nil, 'gitter_room': 'open-data')
Topic.create(name: 'operating-systems', 'search_index': 'operating-systems', namespace: nil, 'gitter_room': 'operating-systems')
Topic.create(name: 'opsec', 'search_index': 'opsec', namespace: nil, 'gitter_room': 'opsec')
Topic.create(name: 'optimization', 'search_index': 'optimization', namespace: nil, 'gitter_room': 'optimization')
Topic.create(name: 'other', 'search_index': 'other', namespace: nil, 'gitter_room': 'other')
Topic.create(name: 'outdoors', 'search_index': 'outdoors', namespace: nil, 'gitter_room': 'outdoors')
Topic.create(name: 'outer-space', 'search_index': 'outer-space', namespace: nil, 'gitter_room': 'outer-space')
Topic.create(name: 'parenting', 'search_index': 'parenting', namespace: nil, 'gitter_room': 'parenting')
Topic.create(name: 'patent', 'search_index': 'patent', namespace: nil, 'gitter_room': 'patent')
Topic.create(name: 'pets', 'search_index': 'pets', namespace: nil, 'gitter_room': 'pets')
Topic.create(name: 'philosophy', 'search_index': 'philosophy', namespace: nil, 'gitter_room': 'philosophy')
Topic.create(name: 'photography', 'search_index': 'photography', namespace: nil, 'gitter_room': 'photography')
Topic.create(name: 'physics', 'search_index': 'physics', namespace: nil, 'gitter_room': 'physics')
Topic.create(name: 'piano', 'search_index': 'piano', namespace: nil, 'gitter_room': 'piano')
Topic.create(name: 'poetry', 'search_index': 'poetry', namespace: nil, 'gitter_room': 'poetry')
Topic.create(name: 'poker', 'search_index': 'poker', namespace: nil, 'gitter_room': 'poker')
Topic.create(name: 'politics', 'search_index': 'politics', namespace: nil, 'gitter_room': 'politics')
Topic.create(name: 'privacy', 'search_index': 'privacy', namespace: nil, 'gitter_room': 'privacy')
Topic.create(name: 'productivity', 'search_index': 'productivity', namespace: nil, 'gitter_room': 'productivity')
Topic.create(name: 'programming', 'search_index': 'programming', namespace: nil, 'gitter_room': 'programming')
Topic.create(name: 'agda', 'search_index': 'programming-languages/agda', namespace: 'programming-languages', 'gitter_room': 'programming-languages/agda')
Topic.create(name: 'assembly', 'search_index': 'programming-languages/assembly', namespace: 'programming-languages', 'gitter_room': 'programming-languages/assembly')
Topic.create(name: 'c', 'search_index': 'programming-languages/c', namespace: 'programming-languages', 'gitter_room': 'programming-languages/c')
Topic.create(name: 'c++', 'search_index': 'programming-languages/c++', namespace: 'programming-languages', 'gitter_room': 'programming-languages/c++')
Topic.create(name: 'clojure', 'search_index': 'programming-languages/clojure', namespace: 'programming-languages', 'gitter_room': 'programming-languages/clojure')
Topic.create(name: 'coq', 'search_index': 'programming-languages/coq', namespace: 'programming-languages', 'gitter_room': 'programming-languages/coq')
Topic.create(name: 'css', 'search_index': 'programming-languages/css', namespace: 'programming-languages', 'gitter_room': 'programming-languages/css')
Topic.create(name: 'd', 'search_index': 'programming-languages/d', namespace: 'programming-languages', 'gitter_room': 'programming-languages/d')
Topic.create(name: 'dotnet', 'search_index': 'programming-languages/dotnet', namespace: 'programming-languages', 'gitter_room': 'programming-languages/dotnet')
Topic.create(name: 'go', 'search_index': 'programming-languages/go', namespace: 'programming-languages', 'gitter_room': 'programming-languages/go')
Topic.create(name: 'graphql', 'search_index': 'programming-languages/graphql', namespace: 'programming-languages', 'gitter_room': 'programming-languages/graphql')
Topic.create(name: 'haskell', 'search_index': 'programming-languages/haskell', namespace: 'programming-languages', 'gitter_room': 'programming-languages/haskell')
Topic.create(name: 'idris', 'search_index': 'programming-languages/idris', namespace: 'programming-languages', 'gitter_room': 'programming-languages/idris')
Topic.create(name: 'java', 'search_index': 'programming-languages/java', namespace: 'programming-languages', 'gitter_room': 'programming-languages/java')
Topic.create(name: 'javascript', 'search_index': 'programming-languages/javascript', namespace: 'programming-languages', 'gitter_room': 'programming-languages/javascript')
Topic.create(name: 'kotlin', 'search_index': 'programming-languages/kotlin', namespace: 'programming-languages', 'gitter_room': 'programming-languages/kotlin')
Topic.create(name: 'lisp', 'search_index': 'programming-languages/lisp', namespace: 'programming-languages', 'gitter_room': 'programming-languages/lisp')
Topic.create(name: 'ocaml', 'search_index': 'programming-languages/ocaml', namespace: 'programming-languages', 'gitter_room': 'programming-languages/ocaml')
Topic.create(name: 'perl', 'search_index': 'programming-languages/perl', namespace: 'programming-languages', 'gitter_room': 'programming-languages/perl')
Topic.create(name: 'php', 'search_index': 'programming-languages/php', namespace: 'programming-languages', 'gitter_room': 'programming-languages/php')
Topic.create(name: 'prolog', 'search_index': 'programming-languages/prolog', namespace: 'programming-languages', 'gitter_room': 'programming-languages/prolog')
Topic.create(name: 'purescript', 'search_index': 'programming-languages/purescript', namespace: 'programming-languages', 'gitter_room': 'programming-languages/purescript')
Topic.create(name: 'python', 'search_index': 'programming-languages/python', namespace: 'programming-languages', 'gitter_room': 'programming-languages/python')
Topic.create(name: 'r', 'search_index': 'programming-languages/r', namespace: 'programming-languages', 'gitter_room': 'programming-languages/r')
Topic.create(name: 'reasonml', 'search_index': 'programming-languages/reasonml', namespace: 'programming-languages', 'gitter_room': 'programming-languages/reasonml')
Topic.create(name: 'ruby', 'search_index': 'programming-languages/ruby', namespace: 'programming-languages', 'gitter_room': 'programming-languages/ruby')
Topic.create(name: 'rust', 'search_index': 'programming-languages/rust', namespace: 'programming-languages', 'gitter_room': 'programming-languages/rust')
Topic.create(name: 'scala', 'search_index': 'programming-languages/scala', namespace: 'programming-languages', 'gitter_room': 'programming-languages/scala')
Topic.create(name: 'smalltalk', 'search_index': 'programming-languages/smalltalk', namespace: 'programming-languages', 'gitter_room': 'programming-languages/smalltalk')
Topic.create(name: 'swift', 'search_index': 'programming-languages/swift', namespace: 'programming-languages', 'gitter_room': 'programming-languages/swift')
Topic.create(name: 'tex', 'search_index': 'programming-languages/tex', namespace: 'programming-languages', 'gitter_room': 'programming-languages/tex')
Topic.create(name: 'typescript', 'search_index': 'programming-languages/typescript', namespace: 'programming-languages', 'gitter_room': 'programming-languages/typescript')
Topic.create(name: 'project-management', 'search_index': 'project-management', namespace: nil, 'gitter_room': 'project-management')
Topic.create(name: 'psychedelics', 'search_index': 'psychedelics', namespace: nil, 'gitter_room': 'psychedelics')
Topic.create(name: 'psychology', 'search_index': 'psychology', namespace: nil, 'gitter_room': 'psychology')
Topic.create(name: 'quantitative-finance', 'search_index': 'quantitative-finance', namespace: nil, 'gitter_room': 'quantitative-finance')
Topic.create(name: 'quantum-computing', 'search_index': 'quantum-computing', namespace: nil, 'gitter_room': 'quantum-computing')
Topic.create(name: 'quantum-physics', 'search_index': 'quantum-physics', namespace: nil, 'gitter_room': 'quantum-physics')
Topic.create(name: 'radiiology', 'search_index': 'radiiology', namespace: nil, 'gitter_room': 'radiiology')
Topic.create(name: 'raspberry-pi', 'search_index': 'raspberry-pi', namespace: nil, 'gitter_room': 'raspberry-pi')
Topic.create(name: 'reading', 'search_index': 'reading', namespace: nil, 'gitter_room': 'reading')
Topic.create(name: 'regular-expression', 'search_index': 'regular-expression', namespace: nil, 'gitter_room': 'regular-expression')
Topic.create(name: 'reinforcement-learning', 'search_index': 'reinforcement-learning', namespace: nil, 'gitter_room': 'reinforcement-learning')
Topic.create(name: 'relationships', 'search_index': 'relationships', namespace: nil, 'gitter_room': 'relationships')
Topic.create(name: 'reverse-engineering', 'search_index': 'reverse-engineering', namespace: nil, 'gitter_room': 'reverse-engineering')
Topic.create(name: 'robotics', 'search_index': 'robotics', namespace: nil, 'gitter_room': 'robotics')
Topic.create(name: 'sales', 'search_index': 'sales', namespace: nil, 'gitter_room': 'sales')
Topic.create(name: 'science', 'search_index': 'science', namespace: nil, 'gitter_room': 'science')
Topic.create(name: 'scifi', 'search_index': 'scifi', namespace: nil, 'gitter_room': 'scifi')
Topic.create(name: 'scripted-audio', 'search_index': 'scripted-audio', namespace: nil, 'gitter_room': 'scripted-audio')
Topic.create(name: 'security', 'search_index': 'security', namespace: nil, 'gitter_room': 'security')
Topic.create(name: 'seo', 'search_index': 'seo', namespace: nil, 'gitter_room': 'seo')
Topic.create(name: 'server-fault', 'search_index': 'server-fault', namespace: nil, 'gitter_room': 'server-fault')
Topic.create(name: 'signal-processing', 'search_index': 'signal-processing', namespace: nil, 'gitter_room': 'signal-processing')
Topic.create(name: 'sleep', 'search_index': 'sleep', namespace: nil, 'gitter_room': 'sleep')
Topic.create(name: 'society', 'search_index': 'society', namespace: nil, 'gitter_room': 'society')
Topic.create(name: 'software-engineering', 'search_index': 'software-engineering', namespace: nil, 'gitter_room': 'software-engineering')
Topic.create(name: 'android', 'search_index': 'software-tools/android', namespace: 'software-tools', 'gitter_room': 'software-tools/android')
Topic.create(name: 'drupal', 'search_index': 'software-tools/drupal', namespace: 'software-tools', 'gitter_room': 'software-tools/drupal')
Topic.create(name: 'emacs', 'search_index': 'software-tools/emacs', namespace: 'software-tools', 'gitter_room': 'software-tools/emacs')
Topic.create(name: 'excel', 'search_index': 'software-tools/excel', namespace: 'software-tools', 'gitter_room': 'software-tools/excel')
Topic.create(name: 'expression-engine', 'search_index': 'software-tools/expression-engine', namespace: 'software-tools', 'gitter_room': 'software-tools/expression-engine')
Topic.create(name: 'git', 'search_index': 'software-tools/git', namespace: 'software-tools', 'gitter_room': 'software-tools/git')
Topic.create(name: 'integrated-development-environments', 'search_index': 'software-tools/integrated-development-environments', namespace: 'software-tools', 'gitter_room': 'software-tools/integrated-development-environments')
Topic.create(name: 'ios', 'search_index': 'software-tools/ios', namespace: 'software-tools', 'gitter_room': 'software-tools/ios')
Topic.create(name: 'kubernetes', 'search_index': 'software-tools/kubernetes', namespace: 'software-tools', 'gitter_room': 'software-tools/kubernetes')
Topic.create(name: 'linux', 'search_index': 'software-tools/linux', namespace: 'software-tools', 'gitter_room': 'software-tools/linux')
Topic.create(name: 'nodejs', 'search_index': 'software-tools/nodejs', namespace: 'software-tools', 'gitter_room': 'software-tools/nodejs')
Topic.create(name: 'postgresql', 'search_index': 'software-tools/postgresql', namespace: 'software-tools', 'gitter_room': 'software-tools/postgresql')
Topic.create(name: 'powershell', 'search_index': 'software-tools/powershell', namespace: 'software-tools', 'gitter_room': 'software-tools/powershell')
Topic.create(name: 'react', 'search_index': 'software-tools/react', namespace: 'software-tools', 'gitter_room': 'software-tools/react')
Topic.create(name: 'redux', 'search_index': 'software-tools/redux', namespace: 'software-tools', 'gitter_room': 'software-tools/redux')
Topic.create(name: 'salesforce', 'search_index': 'software-tools/salesforce', namespace: 'software-tools', 'gitter_room': 'software-tools/salesforce')
Topic.create(name: 'sharepoint', 'search_index': 'software-tools/sharepoint', namespace: 'software-tools', 'gitter_room': 'software-tools/sharepoint')
Topic.create(name: 'tor', 'search_index': 'software-tools/tor', namespace: 'software-tools', 'gitter_room': 'software-tools/tor')
Topic.create(name: 'ubuntu', 'search_index': 'software-tools/ubuntu', namespace: 'software-tools', 'gitter_room': 'software-tools/ubuntu')
Topic.create(name: 'unix', 'search_index': 'software-tools/unix', namespace: 'software-tools', 'gitter_room': 'software-tools/unix')
Topic.create(name: 'v8engine', 'search_index': 'software-tools/v8engine', namespace: 'software-tools', 'gitter_room': 'software-tools/v8engine')
Topic.create(name: 'vim', 'search_index': 'software-tools/vim', namespace: 'software-tools', 'gitter_room': 'software-tools/vim')
Topic.create(name: 'webpack', 'search_index': 'software-tools/webpack', namespace: 'software-tools', 'gitter_room': 'software-tools/webpack')
Topic.create(name: 'wordpress', 'search_index': 'software-tools/wordpress', namespace: 'software-tools', 'gitter_room': 'software-tools/wordpress')
Topic.create(name: 'sound-design', 'search_index': 'sound-design', namespace: nil, 'gitter_room': 'sound-design')
Topic.create(name: 'spaced-repetition', 'search_index': 'spaced-repetition', namespace: nil, 'gitter_room': 'spaced-repetition')
Topic.create(name: 'sports', 'search_index': 'sports', namespace: nil, 'gitter_room': 'sports')
Topic.create(name: 'sprituality', 'search_index': 'sprituality', namespace: nil, 'gitter_room': 'sprituality')
Topic.create(name: 'stack', 'search_index': 'stack', namespace: nil, 'gitter_room': 'stack')
Topic.create(name: 'startups', 'search_index': 'startups', namespace: nil, 'gitter_room': 'startups')
Topic.create(name: 'statistics', 'search_index': 'statistics', namespace: nil, 'gitter_room': 'statistics')
Topic.create(name: 'strategy', 'search_index': 'strategy', namespace: nil, 'gitter_room': 'strategy')
Topic.create(name: 'super-user', 'search_index': 'super-user', namespace: nil, 'gitter_room': 'super-user')
Topic.create(name: 'sustainable-living', 'search_index': 'sustainable-living', namespace: nil, 'gitter_room': 'sustainable-living')
Topic.create(name: 'swimming', 'search_index': 'swimming', namespace: nil, 'gitter_room': 'swimming')
Topic.create(name: 'tamil-language', 'search_index': 'tamil-language', namespace: nil, 'gitter_room': 'tamil-language')
Topic.create(name: 'teaching', 'search_index': 'teaching', namespace: nil, 'gitter_room': 'teaching')
Topic.create(name: 'technology', 'search_index': 'technology', namespace: nil, 'gitter_room': 'technology')
Topic.create(name: 'telecommunication', 'search_index': 'telecommunication', namespace: nil, 'gitter_room': 'telecommunication')
Topic.create(name: 'template', 'search_index': 'template', namespace: nil, 'gitter_room': 'template')
Topic.create(name: 'thinking', 'search_index': 'thinking', namespace: nil, 'gitter_room': 'thinking')
Topic.create(name: 'timezones', 'search_index': 'timezones', namespace: nil, 'gitter_room': 'timezones')
Topic.create(name: 'travel', 'search_index': 'travel', namespace: nil, 'gitter_room': 'travel')
Topic.create(name: 'type-theory', 'search_index': 'type-theory', namespace: nil, 'gitter_room': 'type-theory')
Topic.create(name: 'universe', 'search_index': 'universe', namespace: nil, 'gitter_room': 'universe')
Topic.create(name: 'vehicle', 'search_index': 'vehicle', namespace: nil, 'gitter_room': 'vehicle')
Topic.create(name: 'video', 'search_index': 'video', namespace: nil, 'gitter_room': 'video')
Topic.create(name: 'visualization', 'search_index': 'visualization', namespace: nil, 'gitter_room': 'visualization')
Topic.create(name: 'wealth', 'search_index': 'wealth', namespace: nil, 'gitter_room': 'wealth')
Topic.create(name: 'web', 'search_index': 'web', namespace: nil, 'gitter_room': 'web')
Topic.create(name: 'web-design', 'search_index': 'web-design', namespace: nil, 'gitter_room': 'web-design')
Topic.create(name: 'web-development', 'search_index': 'web-development', namespace: nil, 'gitter_room': 'web-development')
Topic.create(name: 'webgl', 'search_index': 'webgl', namespace: nil, 'gitter_room': 'webgl')
Topic.create(name: 'webmasters', 'search_index': 'webmasters', namespace: nil, 'gitter_room': 'webmasters')
Topic.create(name: 'work-place', 'search_index': 'work-place', namespace: nil, 'gitter_room': 'work-place')
Topic.create(name: 'world-building', 'search_index': 'world-building', namespace: nil, 'gitter_room': 'world-building')
Topic.create(name: 'writing', 'search_index': 'writing', namespace: nil, 'gitter_room': 'writing')

# Person.create!(name: 'Barbara Oakley')
# Person.create!(name: 'Josh Waitzkin')
# sivers = Person.create!(name: 'Derek Sivers', twitter: 'sivers', website: 'https://sivers.org/')
# nicky = Person.create!(name: 'Nicky Case', twitter: 'ncasenmare', website: 'https://ncase.me')

=begin
th = IdeaSet.create!(name: 'learning how to learn')
TopicIdeaSet.create!(topic: learning, idea_set: th)

th = IdeaSet.create!(name: 'the art of learning')
TopicIdeaSet.create!(topic: learning, idea_set: th)

th = IdeaSet.create!(name: 'how to remember anything forever')
TopicIdeaSet.create!(topic: learning, idea_set: th)
PersonIdeaSet.create!(person: nicky, idea_set: th, role: 'creator')
it = Item.create!(idea_set: th, name: th.name, item_type_id: 'interactive')
Link.create!(item: it, url: 'https://ncase.me/remember/')

th = IdeaSet.create!(name: 'there is no speed limit')
TopicIdeaSet.create!(topic: learning, idea_set: th)
PersonIdeaSet.create!(person: sivers, idea_set: th, role: 'creator')
it = Item.create!(idea_set: th, name: th.name, item_type_id: 'article')
Link.create!(item: it, url: 'https://sivers.org/kimo')

th = IdeaSet.create!(name: 'how people learn')
TopicThing.create!(topic: learning, idea_set: th)
=end

# th = learning.idea_sets.create!(
# 	name: 'how to remember anything forever',
# 	items_attributes: [
# 		{
# 			name: 'how to remember anything forever',
# 			item_type_id: 'interactive',
# 			links_attributes: [
# 				{url: 'https://ncase.me/remember/'}
# 			]
# 		}
# 	]
# )

# PersonIdeaSet.create!(person: nicky, idea_set: th, role: 'creator')

